### ISSUE TITLE
Possible wrong patch list/order

### ISSUE THREAD

**Issue by rolesyuk** [nine7nine/pkgbuilds_nspa#4]
I've tried to apply your patches (to build the package under Ubuntu) in the order listed in PKGBUILD and failed:
```
/media/storage/roman/Projects/wine/wine-5.9
Applying /media/storage/roman/Projects/wine/pkgbuilds_nspa/wine-nspa/use_clock_monotonic.patch ...
Applying /media/storage/roman/Projects/wine/pkgbuilds_nspa/wine-nspa/fsync-staging.patch ...
Applying /media/storage/roman/Projects/wine/pkgbuilds_nspa/wine-nspa/fsync-staging-no_alloc_handle.patch ...
Applying /media/storage/roman/Projects/wine/pkgbuilds_nspa/wine-nspa/fsync-spincounts.patch ...
Applying /media/storage/roman/Projects/wine/pkgbuilds_nspa/wine-nspa/0003-Exit-expand-function-early-if-there-are-no-children.patch ...
Applying /media/storage/roman/Projects/wine/pkgbuilds_nspa/wine-nspa/0056-allow-WINEDLLPATH-override.patch ...
Applying /media/storage/roman/Projects/wine/pkgbuilds_nspa/wine-nspa/ableton_file-read-write-diff.patch ...
Applying /media/storage/roman/Projects/wine/pkgbuilds_nspa/wine-nspa/disable-winedbg-auto-crash-dialog.patch ...
Applying /media/storage/roman/Projects/wine/pkgbuilds_nspa/wine-nspa/disable-wine-prefix-update-window.patch ...
Applying /media/storage/roman/Projects/wine/pkgbuilds_nspa/wine-nspa/hack-for-Ivory-Library-Installer-force-GENERIC_xxx.patch ...
Applying /media/storage/roman/Projects/wine/pkgbuilds_nspa/wine-nspa/NI-drag-and-drop.patch ...
Applying /media/storage/roman/Projects/wine/pkgbuilds_nspa/wine-nspa/0001-wineserver-Draft-to-implement-priority-levels-throug.patch ...
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file server/Makefile.in.rej
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file server/main.c.rej
The next patch would create the file server/scheduler.c,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file server/thread.c.rej
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file server/thread.h.rej
```

**Comment by nine7nine** [comment]
invalid issue. why?

it failed because you are trying to apply a patch, that must be reversed; before applying my RT related patches. look at my wine-nspa pkgbuild, it clearly shows;

patch -s -Rp1 -i $srcdir/0001-wineserver-Draft-to-implement-priority-levels-throug.patch

see -R is reverse, not apply. my RT patch borrows code from the above patch -- and therefore conflicts with it.  So it must be reversed from wine(-staging), before any of my RT related patches get applied.

**Comment by nine7nine** [comment]
thanks for bringing this to my attention;

I'll make the 2 reversed patches more clearly noted in my pkgbuild, next update.

that way people who are on other distros, don't miss that part.

**Comment by rolesyuk** [comment]
Yes, my bad, missed these two letters... Thank you for the clarification. I wrote a simple shell script for Ubuntu 20.04 to build the DEBs. It is here https://github.com/rolesyuk/rt_audio/blob/master/wine/build.sh in the case someone needs it.

**Comment by rolesyuk** [comment]
Great work, by the way! :thumbsup: Keep it on!

**Comment by rolesyuk** [comment]
I've published Ubuntu 20.04 DEBs (maybe someone needs it) for the plain kernel + REEMPT_RT + FUTEX_WAIT_MULTIPLE patches and WINE + NSPA patches here https://github.com/rolesyuk/rt_audio/releases/tag/v12

**Comment by nine7nine** [comment]
bro, this is awesome - i know people who want to try out my builds on Ubuntu, but they wouldn't be able to package it up (or even patch/build from source).

I might add this to the README, if you don't mind?

**Comment by rolesyuk** [comment]
Sure! It would be great. I will try to follow your work and update the packages accordingly in the future.

**Comment by nine7nine** [comment]
Okay, once we solve your other issue on my github about Jack, I can look at adding links to your packages + any troubleshooting or steps needed to get things working...

I appreciate you building binaries for Ubuntu. very cool.

**Comment by nine7nine** [comment]
regarding the pkgbuild and reversed patches -- as I said i would, I've added a note/comment about it in the pkgbuild, as well as making it more clear that the patches are reversed.
