### ISSUE TITLE
With ENABLE_UPDATE_WINDOW=0 wine fails to create a new prefix. (TODO: modify to disallow creating prefixes, if =0 set)

### ISSUE THREAD

**Issue by rolesyuk** [nine7nine/pkgbuilds_nspa#6]
ProgramData, 'Program Files' and 'Program Files (x86)' directories are not created, DLLs are not installed which does not allow to install most of the programs...

```
roman@ryzen ~ rm -rf ${HOME}/wine-test-prefix; ENABLE_UPDATE_WINDOW=0 WINEPREFIX=${HOME}/wine-test-prefix winecfg; ls -l ${HOME}/wine-test-prefix/drive_c
wine: created the configuration directory '/home/roman/wine-test-prefix'
wine: configuration in L"/home/roman/wine-test-prefix" has been updated.
total 8
drwxrwxr-x 3 roman roman 4096 июл  8 13:30 users
drwxrwxr-x 4 roman roman 4096 июл  8 13:30 windows

roman@ryzen ~ rm -rf ${HOME}/wine-test-prefix; ENABLE_UPDATE_WINDOW=1 WINEPREFIX=${HOME}/wine-test-prefix winecfg; ls -l ${HOME}/wine-test-prefix/drive_c
wine: created the configuration directory '/home/roman/wine-test-prefix'
wine: configuration in L"/home/roman/wine-test-prefix" has been updated.
total 20
drwxrwxr-x  3 roman roman 4096 июл  8 13:30  ProgramData
drwxrwxr-x  6 roman roman 4096 июл  8 13:30 'Program Files'
drwxrwxr-x  6 roman roman 4096 июл  8 13:31 'Program Files (x86)'
drwxrwxr-x  4 roman roman 4096 июл  8 13:30  users
drwxrwxr-x 19 roman roman 4096 июл  8 13:31  windows
```
A list of all files in the prefix in the attachment as an output of:
```
rm -rf ${HOME}/wine-test-prefix; ENABLE_UPDATE_WINDOW=0 WINEPREFIX=${HOME}/wine-test-prefix winecfg; find ${HOME}/wine-test-prefix/drive_c > find_ENABLE_UPDATE_WINDOW_0.txt
rm -rf ${HOME}/wine-test-prefix; ENABLE_UPDATE_WINDOW=1 WINEPREFIX=${HOME}/wine-test-prefix winecfg; find ${HOME}/wine-test-prefix/drive_c > find_ENABLE_UPDATE_WINDOW_1.txt
```
[find_ENABLE_UPDATE_WINDOW_0.txt](https://github.com/nine7nine/pkgbuilds_nspa/files/4890150/find_ENABLE_UPDATE_WINDOW_0.txt)
[find_ENABLE_UPDATE_WINDOW_1.txt](https://github.com/nine7nine/pkgbuilds_nspa/files/4890151/find_ENABLE_UPDATE_WINDOW_1.txt)

**Comment by nine7nine** [comment]
nice catch.

i'm dumb and forgot to note in the README about switching to =1 when creating prefixes... I'll add that bit in.

i think I'll also poke around the related code -- maybe i can adapt/revise the patch in a couple of ways;

- disallow creating a prefix entirely, if =1 isn't set. (which would avoid the failing to create it)
- print a message, telling the user to =1 to create prefixes.

**Comment by nine7nine** [comment]
- updated the README.
- edited the issue: as this is a bug + feature enhancement now.

once i get this working as intended; I'll probably change the env variable name. As this will no longer be just about disabling the update window, but disallowing creating wine-prefixes, in general.

WINE_NSPAPREFIX

something like the above would actually be more consistent with other wine env variables anyway.

**Comment by nine7nine** [comment]
https://github.com/nine7nine/pkgbuilds_nspa/commit/a38a8dc8a036c85828d2d47efe6713747ecfc37b

I disabled the patch for now. I think that's the best option - until I figure out a better solution. I have some ideas on this, so testing out a few things. I'll add back a hack to do this -- when i'm satisfied it's good enough / no rough edges.

PS: Also bumped the version, due to this and changes in RT patch.

**Comment by nine7nine** [comment]
I'm thinking about removing the wineboot.c update window code, rather than having an override.

this avoids adding another env variable -- and the patch I'm currently testing creates prefixes fine. it does throw an extra couple of fixme: - but they are harmless.

what do you think, Roman? Does that seem like an acceptable solution?

**Comment by rolesyuk** [comment]
Looks good for me as far as it does not interfere with the actual update process.

**Comment by nine7nine** [comment]
k. that's what i'm going to do then.

I'll add the patch for the next update, once i have something more substantial (other patchwork i'm working on) sorted out, for a version bump.

**Comment by rolesyuk** [comment]
It would be great!

**Comment by nine7nine** [comment]
https://github.com/nine7nine/pkgbuilds_nspa/blob/master/wine-nspa/nspa_wineboot-remove_update_window_hack.patch

Patch added to v5.9.19
